name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Build (no features enabled)
      run: cargo build --verbose

    - name: Build (all features enabled)
      run: cargo build --verbose --all-features

  Build-Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: install nasm
      run: |
        choco install nasm
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build (no features enabled)
      run: cargo build --verbose

    - name: Build (all features enabled)
      run: cargo build --verbose --all-features

  Build-WASM:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Install target
      run: |
        rustup toolchain add 1.88.0
        rustup target add --toolchain 1.88.0 wasm32-wasip1

    - name: Build (WASM-compatible features)
      run: cargo +1.88.0 build --verbose --target wasm32-wasip1 --no-default-features --features flate2,ring -p russh
